"use client";
import React, { useState } from 'react';
import Link from 'next/link';
import { Icon } from '@/components/ui/Icon';
import { FilterPopover, FilterField, SortOption } from '@/components/ui/FilterPopover';
import { ExportButton } from '@/components/ui/ExportButton';
import { useToast } from '@/components/ui/Toast';
import { PrintDocumentModal, BarcodeScanInput } from '@/components/ui/BarcodeDisplay';

const SERVICE_ORDERS = [
  { id: 'SO-2026-0881', unit: 'MSKU 744218-3', type: '20GP', customer: 'C-00142', custName: 'Thai Union Group', code: 'STORAGE-L', desc: 'Storage, laden (4 days)', amount: '฿320.00', date: '2026-04-24 14:30', status: 'Pending' },
  { id: 'SO-2026-0882', unit: 'MSKU 744218-3', type: '20GP', customer: 'C-00142', custName: 'Thai Union Group', code: 'LIFT-ON', desc: 'Container lift-on', amount: '฿850.00', date: '2026-04-24 14:30', status: 'Pending' },
  { id: 'SO-2026-0879', unit: 'TCLU 199245-0', type: '40HC', customer: 'C-00308', custName: 'PTT Global Chemical', code: 'GATE-IN', desc: 'Gate entry processing', amount: '฿120.00', date: '2026-04-24 11:15', status: 'Invoiced' },
  { id: 'SO-2026-0878', unit: 'TCLU 199245-0', type: '40HC', customer: 'C-00308', custName: 'PTT Global Chemical', code: 'LIFT-OFF', desc: 'Container lift-off', amount: '฿850.00', date: '2026-04-24 11:20', status: 'Invoiced' },
  { id: 'SO-2026-0875', unit: 'HLXU 441920-8', type: '40RF', customer: 'C-00412', custName: 'CP Foods Co.', code: 'RF-PLUG', desc: 'Reefer monitoring (2 days)', amount: '฿840.00', date: '2026-04-23 09:00', status: 'Pending' },
  { id: 'SO-2026-0870', unit: 'HLXU 441920-8', type: '40RF', customer: 'C-00412', custName: 'CP Foods Co.', code: 'DG-HNDL', desc: 'Dangerous goods handling', amount: '฿1,200.00', date: '2026-04-23 09:00', status: 'Cancelled' },
  { id: 'SO-2026-0862', unit: 'CXDU 881234-5', type: '20OT', customer: 'C-00211', custName: 'Siam Cement Group', code: 'SHIFTING', desc: 'In-yard repositioning', amount: '฿480.00', date: '2026-04-22 16:45', status: 'Pending' },
];

const SO_FILTER_FIELDS: FilterField[] = [
  { type: 'search', key: 'query', placeholder: 'Search SO number, unit, customer...' },
  { type: 'select', key: 'code', label: 'Charge Code', options: [{ label: 'All', value: '' }, { label: 'STORAGE-L', value: 'storage-l' }, { label: 'LIFT-ON', value: 'lift-on' }, { label: 'GATE-IN', value: 'gate-in' }, { label: 'RF-PLUG', value: 'rf-plug' }] },
  { type: 'select', key: 'status', label: 'Status', options: [{ label: 'All', value: '' }, { label: 'Pending', value: 'pending' }, { label: 'Invoiced', value: 'invoiced' }, { label: 'Cancelled', value: 'cancelled' }] },
  { type: 'select', key: 'date', label: 'Date range', options: [{ label: 'All time', value: '' }, { label: 'Today', value: 'today' }, { label: 'Last 7 days', value: '7d' }, { label: 'Last 30 days', value: '30d' }] },
];

const SO_SORT_OPTIONS: SortOption[] = [
  { label: 'Date (newest)', value: 'date_desc' },
  { label: 'Amount (high → low)', value: 'amount_desc' },
  { label: 'SO Number', value: 'id' },
  { label: 'Customer', value: 'customer' },
];

function StatusBadge({ status }: { status: string }) {
  if (status === 'Pending') return <span style={{ background: 'var(--gecko-warning-100)', color: 'var(--gecko-warning-700)', padding: '2px 8px', borderRadius: 12, fontSize: 11, fontWeight: 700 }}>Pending</span>;
  if (status === 'Invoiced') return <span style={{ background: 'var(--gecko-success-100)', color: 'var(--gecko-success-700)', padding: '2px 8px', borderRadius: 12, fontSize: 11, fontWeight: 700 }}>Invoiced</span>;
  if (status === 'Cancelled') return <span style={{ background: 'var(--gecko-gray-200)', color: 'var(--gecko-text-secondary)', padding: '2px 8px', borderRadius: 12, fontSize: 11, fontWeight: 700 }}>Cancelled</span>;
  return null;
}

export default function ServiceOrdersPage() {
  const [filters, setFilters] = useState<Record<string, string>>({ query: '', code: '', status: 'pending', date: '' });
  const [sortBy, setSortBy] = useState('date_desc');
  const { toast } = useToast();
  const [printDoc, setPrintDoc] = useState<{ id: string; docType: string; details: {label:string;value:string}[] } | null>(null);
  const [scannedId, setScannedId] = useState<string | null>(null);

  return (
    <div style={{ maxWidth: 'var(--gecko-container-max)', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 24, paddingBottom: 40 }}>

      {/* Header */}
      <div className="gecko-page-actions">
        <div className="gecko-page-actions-left">
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}>
            <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0, color: 'var(--gecko-text-primary)' }}>Service Orders</h1>
            <span className="gecko-count-badge">7 shown of 1,240</span>
          </div>
          <div style={{ fontSize: 13, color: 'var(--gecko-text-secondary)' }}>Atomic chargeable events generated by yard activity or manual entry. Ready for invoicing.</div>
        </div>
        <div className="gecko-toolbar">
          <ExportButton resource="Service orders" iconSize={16} />
          <BarcodeScanInput onScan={v => setScannedId(v)} placeholder="Scan SO number…" size="sm" style={{ width: 200 }} />
          <FilterPopover
            fields={SO_FILTER_FIELDS}
            values={filters}
            onChange={setFilters}
            onApply={(v) => setFilters(v)}
            onClear={() => setFilters({ query: '', code: '', status: '', date: '' })}
            sortOptions={SO_SORT_OPTIONS}
            sortValue={sortBy}
            onSortChange={setSortBy}
          />
          <button className="gecko-btn gecko-btn-primary gecko-btn-sm" onClick={() => toast({ variant: 'info', title: 'Manual Charge', message: 'Manual-charge entry form coming soon.' })}><Icon name="plus" size={16} /> Manual Charge</button>
        </div>
      </div>

      {/* Table */}
      <div style={{ background: 'var(--gecko-bg-surface)', border: '1px solid var(--gecko-border)', borderRadius: 12, overflow: 'hidden', boxShadow: 'var(--gecko-shadow-sm)' }}>
        <table className="gecko-table gecko-table-comfortable" style={{ fontSize: 13 }}>
          <thead>
            <tr>
              <th>SO Number</th>
              <th>Date</th>
              <th>Unit / Type</th>
              <th>Customer (Bill-to)</th>
              <th>Charge Code & Desc</th>
              <th style={{ textAlign: 'right' }}>Amount (Excl. VAT)</th>
              <th>Status</th>
              <th style={{ textAlign: 'right' }}></th>
            </tr>
          </thead>
          <tbody>
            {SERVICE_ORDERS.map((so) => (
              <tr key={so.id} style={scannedId === so.id ? { background: 'var(--gecko-primary-50)', borderLeft: '3px solid var(--gecko-primary-500)' } : undefined}>
                <td className="gecko-text-mono" style={{ fontWeight: 600, color: 'var(--gecko-primary-600)' }}>
                  <a href="#" style={{ color: 'inherit', textDecoration: 'none' }}>{so.id}</a>
                </td>
                <td style={{ color: 'var(--gecko-text-secondary)', fontSize: 12 }}>{so.date}</td>
                <td>
                  <div style={{ fontWeight: 600, fontFamily: 'var(--gecko-font-mono)' }}>{so.unit}</div>
                  <div style={{ fontSize: 11, color: 'var(--gecko-text-disabled)', fontFamily: 'var(--gecko-font-mono)' }}>{so.type}</div>
                </td>
                <td>
                  <div style={{ fontWeight: 600, color: 'var(--gecko-text-primary)' }}>{so.custName}</div>
                  <div style={{ fontSize: 11, color: 'var(--gecko-text-disabled)', fontFamily: 'var(--gecko-font-mono)' }}>{so.customer}</div>
                </td>
                <td>
                  <div style={{ fontWeight: 700, color: 'var(--gecko-info-700)', fontFamily: 'var(--gecko-font-mono)', fontSize: 12 }}>{so.code}</div>
                  <div style={{ fontSize: 12, color: 'var(--gecko-text-secondary)' }}>{so.desc}</div>
                </td>
                <td className="gecko-text-mono" style={{ textAlign: 'right', fontWeight: 700 }}>{so.amount}</td>
                <td>
                  <StatusBadge status={so.status} />
                </td>
                <td style={{ textAlign: 'right' }}>
                  <button
                    onClick={() => setPrintDoc({ id: so.id, docType: 'Service Order', details: [
                      { label: 'Unit', value: so.unit },
                      { label: 'Charge Code', value: so.code },
                      { label: 'Customer', value: so.custName },
                      { label: 'Amount', value: so.amount },
                      { label: 'Date', value: so.date },
                      { label: 'Status', value: so.status },
                    ]})}
                    className="gecko-btn gecko-btn-ghost gecko-btn-icon gecko-btn-sm"
                    title="Print / Barcode"
                  >
                    <Icon name="printer" size={13} />
                  </button>
                  <button style={{ background: 'transparent', border: 'none', color: 'var(--gecko-text-disabled)', cursor: 'pointer' }}><Icon name="moreHorizontal" size={16} /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {printDoc && (
        <PrintDocumentModal
          open={!!printDoc}
          onClose={() => setPrintDoc(null)}
          docType={printDoc.docType}
          docNo={printDoc.id}
          barcodeValue={printDoc.id}
          details={printDoc.details}
        />
      )}

    </div>
  );
}
